# Generated by Django 5.2.8 on 2025-11-07 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('damage', models.IntegerField()),
                ('health', models.IntegerField()),
                ('affinity', models.IntegerField(choices=[('FIRE', 1), ('EARTH', 2), ('WATER', 3), ('AIR', 4)])),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='damareen.card')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('boss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dungeon_boss', to='damareen.card')),
                ('cards', models.ManyToManyField(related_name='dungeon_cards', to='damareen.card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='damareen.game')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraHealth', models.IntegerField(default=0)),
                ('extraDamage', models.IntegerField(default=0)),
                ('isBoss', models.BooleanField(default=False)),
                ('extra', models.BooleanField(default=False, null=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='damareen.card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='damareen.game')),
            ],
        ),
    ]
