# Generated by Django 5.2.8 on 2025-11-09 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('damage', models.IntegerField(blank=True)),
                ('health', models.IntegerField(blank=True)),
                ('affinity', models.IntegerField(blank=True, choices=[(1, 'FIRE'), (2, 'EARTH'), (3, 'WATER'), (4, 'AIR')])),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('dungeonType', models.IntegerField(blank=True, choices=[(1, 'SIMPLE'), (2, 'SMALL'), (3, 'BIG')])),
                ('extra', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dungeon_boss', to='damareen.card')),
                ('cards', models.ManyToManyField(blank=True, related_name='dungeon_cards', to='damareen.card')),
                ('game', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='damareen.game')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraHealth', models.IntegerField(default=0)),
                ('extraDamage', models.IntegerField(default=0)),
                ('isBoss', models.BooleanField(default=False)),
                ('extra', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='damareen.card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='damareen.game')),
            ],
        ),
    ]
