# Generated by Django 5.2.8 on 2025-11-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damareen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='affinity',
            field=models.IntegerField(choices=[(1, 'FIRE'), (2, 'EARTH'), (3, 'WATER'), (4, 'AIR')]),
        ),
    ]
