# Generated by Django 5.2.8 on 2025-11-09 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damareen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cards',
        ),
        migrations.AddField(
            model_name='dungeon',
            name='dungeonType',
            field=models.IntegerField(blank=True, choices=[(1, 'SIMPLE'), (2, 'SMALL'), (3, 'BIG')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='affinity',
            field=models.IntegerField(blank=True, choices=[(1, 'FIRE'), (2, 'EARTH'), (3, 'WATER'), (4, 'AIR')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='damage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='health',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dungeon_boss', to='damareen.card'),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='dungeon_cards', to='damareen.card'),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='game',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='damareen.game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playercard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='damareen.card'),
        ),
        migrations.AlterField(
            model_name='playercard',
            name='extra',
            field=models.BooleanField(default=False),
        ),
    ]
