# Generated by Django 5.2.8 on 2025-11-08 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damareen', '0002_alter_card_affinity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='damage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='health',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
