# Generated by Django 5.2.8 on 2025-11-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damareen', '0003_alter_card_damage_alter_card_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercard',
            name='extra',
            field=models.BooleanField(default=False),
        ),
    ]
