# Generated by Django 5.2.8 on 2025-11-08 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damareen', '0005_alter_game_cards_alter_game_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='dungeonType',
            field=models.IntegerField(choices=[(1, 'SIMPLE'), (2, 'SMALL'), (3, 'BIG')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='cards',
            field=models.ManyToManyField(to='damareen.card'),
        ),
    ]
