# Generated by Django 5.2.8 on 2025-11-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damareen', '0006_dungeon_dungeontype_alter_game_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='asd',
            field=models.IntegerField(default=0),
        ),
    ]
