# Generated by Django 5.2.8 on 2025-11-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damareen', '0007_game_asd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='asd',
        ),
    ]
