# Generated by Django 5.2.8 on 2025-11-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damareen', '0008_remove_game_asd'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(default='asd', max_length=7),
            preserve_default=False,
        ),
    ]
