# Generated by Django 5.2.8 on 2025-11-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damareen', '0009_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
