# Generated by Django 5.2.8 on 2025-11-08 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damareen', '0010_alter_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='affinity',
            field=models.IntegerField(blank=True, choices=[(1, 'FIRE'), (2, 'EARTH'), (3, 'WATER'), (4, 'AIR')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='card',
            name='damage',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='health',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
