# Generated by Django 5.2.8 on 2025-11-08 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damareen', '0011_alter_card_affinity_alter_card_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='damage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='health',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dungeon_boss', to='damareen.card'),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='dungeon_cards', to='damareen.card'),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='dungeonType',
            field=models.IntegerField(blank=True, choices=[(1, 'SIMPLE'), (2, 'SMALL'), (3, 'BIG')]),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='game',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='damareen.game'),
        ),
    ]
