# Generated by Django 5.2.8 on 2025-11-09 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damareen', '0012_alter_card_color_alter_card_damage_alter_card_health_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='damareen.card'),
        ),
    ]
