# Generated by Django 5.2.8 on 2025-11-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damareen', '0012_alter_card_color_alter_card_damage_alter_card_health_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='color',
        ),
        migrations.RemoveField(
            model_name='game',
            name='cards',
        ),
    ]
