# Generated by Django 5.2.8 on 2025-11-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damareen', '0013_alter_playercard_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='color',
        ),
        migrations.RemoveField(
            model_name='game',
            name='cards',
        ),
    ]
